// Code generated by internal/tools/interface-wrapper.go; DO NOT EDIT.
package isudbgen

import "database/sql/driver"

type LimitOptionalConnWrappedType = interface {
	driver.Conn
	driver.ConnBeginTx
	driver.ConnPrepareContext
	driver.Execer
	driver.ExecerContext
	driver.NamedValueChecker
	driver.Pinger
	driver.Queryer
	driver.QueryerContext
}

func LimitOptionalConn(v driver.Conn, wrapper func(driver.Conn) LimitOptionalConnWrappedType) driver.Conn {
	wrapped := wrapper(v)
	var i uint64
	const (
		i0 = 1 << iota
		i1
		i2
		i3
		i4
		i5
		i6
		i7
	)
	if _, ok := v.(driver.ConnBeginTx); ok {
		i |= i0
	}
	if _, ok := v.(driver.ConnPrepareContext); ok {
		i |= i1
	}
	if _, ok := v.(driver.Execer); ok {
		i |= i2
	}
	if _, ok := v.(driver.ExecerContext); ok {
		i |= i3
	}
	if _, ok := v.(driver.NamedValueChecker); ok {
		i |= i4
	}
	if _, ok := v.(driver.Pinger); ok {
		i |= i5
	}
	if _, ok := v.(driver.Queryer); ok {
		i |= i6
	}
	if _, ok := v.(driver.QueryerContext); ok {
		i |= i7
	}
	switch i {
	case 0:
		return struct {
			driver.Conn
		}{wrapped}
	case 1:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 2:
		return struct {
			driver.Conn
		}{wrapped}
	case 3:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 4:
		return struct {
			driver.Conn
		}{wrapped}
	case 5:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 6:
		return struct {
			driver.Conn
		}{wrapped}
	case 7:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 8:
		return struct {
			driver.Conn
		}{wrapped}
	case 9:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 10:
		return struct {
			driver.Conn
		}{wrapped}
	case 11:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 12:
		return struct {
			driver.Conn
		}{wrapped}
	case 13:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 14:
		return struct {
			driver.Conn
		}{wrapped}
	case 15:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 16:
		return struct {
			driver.Conn
		}{wrapped}
	case 17:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 18:
		return struct {
			driver.Conn
		}{wrapped}
	case 19:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 20:
		return struct {
			driver.Conn
		}{wrapped}
	case 21:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 22:
		return struct {
			driver.Conn
		}{wrapped}
	case 23:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 24:
		return struct {
			driver.Conn
		}{wrapped}
	case 25:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 26:
		return struct {
			driver.Conn
		}{wrapped}
	case 27:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 28:
		return struct {
			driver.Conn
		}{wrapped}
	case 29:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 30:
		return struct {
			driver.Conn
		}{wrapped}
	case 31:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 32:
		return struct {
			driver.Conn
		}{wrapped}
	case 33:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 34:
		return struct {
			driver.Conn
		}{wrapped}
	case 35:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 36:
		return struct {
			driver.Conn
		}{wrapped}
	case 37:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 38:
		return struct {
			driver.Conn
		}{wrapped}
	case 39:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 40:
		return struct {
			driver.Conn
		}{wrapped}
	case 41:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 42:
		return struct {
			driver.Conn
		}{wrapped}
	case 43:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 44:
		return struct {
			driver.Conn
		}{wrapped}
	case 45:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 46:
		return struct {
			driver.Conn
		}{wrapped}
	case 47:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 48:
		return struct {
			driver.Conn
		}{wrapped}
	case 49:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 50:
		return struct {
			driver.Conn
		}{wrapped}
	case 51:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 52:
		return struct {
			driver.Conn
		}{wrapped}
	case 53:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 54:
		return struct {
			driver.Conn
		}{wrapped}
	case 55:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 56:
		return struct {
			driver.Conn
		}{wrapped}
	case 57:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 58:
		return struct {
			driver.Conn
		}{wrapped}
	case 59:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 60:
		return struct {
			driver.Conn
		}{wrapped}
	case 61:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 62:
		return struct {
			driver.Conn
		}{wrapped}
	case 63:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 64:
		return struct {
			driver.Conn
		}{wrapped}
	case 65:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 66:
		return struct {
			driver.Conn
		}{wrapped}
	case 67:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 68:
		return struct {
			driver.Conn
		}{wrapped}
	case 69:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 70:
		return struct {
			driver.Conn
		}{wrapped}
	case 71:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 72:
		return struct {
			driver.Conn
		}{wrapped}
	case 73:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 74:
		return struct {
			driver.Conn
		}{wrapped}
	case 75:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 76:
		return struct {
			driver.Conn
		}{wrapped}
	case 77:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 78:
		return struct {
			driver.Conn
		}{wrapped}
	case 79:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 80:
		return struct {
			driver.Conn
		}{wrapped}
	case 81:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 82:
		return struct {
			driver.Conn
		}{wrapped}
	case 83:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 84:
		return struct {
			driver.Conn
		}{wrapped}
	case 85:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 86:
		return struct {
			driver.Conn
		}{wrapped}
	case 87:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 88:
		return struct {
			driver.Conn
		}{wrapped}
	case 89:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 90:
		return struct {
			driver.Conn
		}{wrapped}
	case 91:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 92:
		return struct {
			driver.Conn
		}{wrapped}
	case 93:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 94:
		return struct {
			driver.Conn
		}{wrapped}
	case 95:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 96:
		return struct {
			driver.Conn
		}{wrapped}
	case 97:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 98:
		return struct {
			driver.Conn
		}{wrapped}
	case 99:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 100:
		return struct {
			driver.Conn
		}{wrapped}
	case 101:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 102:
		return struct {
			driver.Conn
		}{wrapped}
	case 103:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 104:
		return struct {
			driver.Conn
		}{wrapped}
	case 105:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 106:
		return struct {
			driver.Conn
		}{wrapped}
	case 107:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 108:
		return struct {
			driver.Conn
		}{wrapped}
	case 109:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 110:
		return struct {
			driver.Conn
		}{wrapped}
	case 111:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 112:
		return struct {
			driver.Conn
		}{wrapped}
	case 113:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 114:
		return struct {
			driver.Conn
		}{wrapped}
	case 115:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 116:
		return struct {
			driver.Conn
		}{wrapped}
	case 117:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 118:
		return struct {
			driver.Conn
		}{wrapped}
	case 119:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 120:
		return struct {
			driver.Conn
		}{wrapped}
	case 121:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 122:
		return struct {
			driver.Conn
		}{wrapped}
	case 123:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 124:
		return struct {
			driver.Conn
		}{wrapped}
	case 125:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 126:
		return struct {
			driver.Conn
		}{wrapped}
	case 127:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 128:
		return struct {
			driver.Conn
		}{wrapped}
	case 129:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 130:
		return struct {
			driver.Conn
		}{wrapped}
	case 131:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 132:
		return struct {
			driver.Conn
		}{wrapped}
	case 133:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 134:
		return struct {
			driver.Conn
		}{wrapped}
	case 135:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 136:
		return struct {
			driver.Conn
		}{wrapped}
	case 137:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 138:
		return struct {
			driver.Conn
		}{wrapped}
	case 139:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 140:
		return struct {
			driver.Conn
		}{wrapped}
	case 141:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 142:
		return struct {
			driver.Conn
		}{wrapped}
	case 143:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 144:
		return struct {
			driver.Conn
		}{wrapped}
	case 145:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 146:
		return struct {
			driver.Conn
		}{wrapped}
	case 147:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 148:
		return struct {
			driver.Conn
		}{wrapped}
	case 149:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 150:
		return struct {
			driver.Conn
		}{wrapped}
	case 151:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 152:
		return struct {
			driver.Conn
		}{wrapped}
	case 153:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 154:
		return struct {
			driver.Conn
		}{wrapped}
	case 155:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 156:
		return struct {
			driver.Conn
		}{wrapped}
	case 157:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 158:
		return struct {
			driver.Conn
		}{wrapped}
	case 159:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 160:
		return struct {
			driver.Conn
		}{wrapped}
	case 161:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 162:
		return struct {
			driver.Conn
		}{wrapped}
	case 163:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 164:
		return struct {
			driver.Conn
		}{wrapped}
	case 165:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 166:
		return struct {
			driver.Conn
		}{wrapped}
	case 167:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 168:
		return struct {
			driver.Conn
		}{wrapped}
	case 169:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 170:
		return struct {
			driver.Conn
		}{wrapped}
	case 171:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 172:
		return struct {
			driver.Conn
		}{wrapped}
	case 173:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 174:
		return struct {
			driver.Conn
		}{wrapped}
	case 175:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 176:
		return struct {
			driver.Conn
		}{wrapped}
	case 177:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 178:
		return struct {
			driver.Conn
		}{wrapped}
	case 179:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 180:
		return struct {
			driver.Conn
		}{wrapped}
	case 181:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 182:
		return struct {
			driver.Conn
		}{wrapped}
	case 183:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 184:
		return struct {
			driver.Conn
		}{wrapped}
	case 185:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 186:
		return struct {
			driver.Conn
		}{wrapped}
	case 187:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 188:
		return struct {
			driver.Conn
		}{wrapped}
	case 189:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 190:
		return struct {
			driver.Conn
		}{wrapped}
	case 191:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 192:
		return struct {
			driver.Conn
		}{wrapped}
	case 193:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 194:
		return struct {
			driver.Conn
		}{wrapped}
	case 195:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 196:
		return struct {
			driver.Conn
		}{wrapped}
	case 197:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 198:
		return struct {
			driver.Conn
		}{wrapped}
	case 199:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 200:
		return struct {
			driver.Conn
		}{wrapped}
	case 201:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 202:
		return struct {
			driver.Conn
		}{wrapped}
	case 203:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 204:
		return struct {
			driver.Conn
		}{wrapped}
	case 205:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 206:
		return struct {
			driver.Conn
		}{wrapped}
	case 207:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 208:
		return struct {
			driver.Conn
		}{wrapped}
	case 209:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 210:
		return struct {
			driver.Conn
		}{wrapped}
	case 211:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 212:
		return struct {
			driver.Conn
		}{wrapped}
	case 213:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 214:
		return struct {
			driver.Conn
		}{wrapped}
	case 215:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 216:
		return struct {
			driver.Conn
		}{wrapped}
	case 217:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 218:
		return struct {
			driver.Conn
		}{wrapped}
	case 219:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 220:
		return struct {
			driver.Conn
		}{wrapped}
	case 221:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 222:
		return struct {
			driver.Conn
		}{wrapped}
	case 223:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 224:
		return struct {
			driver.Conn
		}{wrapped}
	case 225:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 226:
		return struct {
			driver.Conn
		}{wrapped}
	case 227:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 228:
		return struct {
			driver.Conn
		}{wrapped}
	case 229:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 230:
		return struct {
			driver.Conn
		}{wrapped}
	case 231:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 232:
		return struct {
			driver.Conn
		}{wrapped}
	case 233:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 234:
		return struct {
			driver.Conn
		}{wrapped}
	case 235:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 236:
		return struct {
			driver.Conn
		}{wrapped}
	case 237:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 238:
		return struct {
			driver.Conn
		}{wrapped}
	case 239:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 240:
		return struct {
			driver.Conn
		}{wrapped}
	case 241:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 242:
		return struct {
			driver.Conn
		}{wrapped}
	case 243:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 244:
		return struct {
			driver.Conn
		}{wrapped}
	case 245:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 246:
		return struct {
			driver.Conn
		}{wrapped}
	case 247:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 248:
		return struct {
			driver.Conn
		}{wrapped}
	case 249:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 250:
		return struct {
			driver.Conn
		}{wrapped}
	case 251:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 252:
		return struct {
			driver.Conn
		}{wrapped}
	case 253:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	case 254:
		return struct {
			driver.Conn
		}{wrapped}
	case 255:
		return struct {
			driver.Conn
			driver.ConnBeginTx
			driver.ConnPrepareContext
			driver.Execer
			driver.ExecerContext
			driver.NamedValueChecker
			driver.Pinger
			driver.Queryer
			driver.QueryerContext
		}{wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped, wrapped}
	}
	return v
}
