// Code generated by iwrapper; DO NOT EDIT.
package isuhttpgen

import (
	"net/http"
	"io"
)

func ResponseWriterWrapper(v http.ResponseWriter, wrapper func(http.ResponseWriter) ResponseWriter) http.ResponseWriter {
	wrapped := wrapper(v)
	var i uint64
	const (
		i0 = 1 << iota
		i1
		i2
		i3
	)
	if _, ok := v.(http.CloseNotifier); ok {
		i |= i0
	}
	if _, ok := v.(http.Flusher); ok {
		i |= i1
	}
	if _, ok := v.(http.Hijacker); ok {
		i |= i2
	}
	if _, ok := v.(io.ReaderFrom); ok {
		i |= i3
	}
	switch i {
	case 0b0:
		return struct {
			http.ResponseWriter
		}{wrapped}
	case 0b1:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
		}{wrapped, wrapped}
	case 0b10:
		return struct {
			http.ResponseWriter
			http.Flusher
		}{wrapped, wrapped}
	case 0b11:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Flusher
		}{wrapped, wrapped, wrapped}
	case 0b100:
		return struct {
			http.ResponseWriter
			http.Hijacker
		}{wrapped, wrapped}
	case 0b101:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
		}{wrapped, wrapped, wrapped}
	case 0b110:
		return struct {
			http.ResponseWriter
			http.Flusher
			http.Hijacker
		}{wrapped, wrapped, wrapped}
	case 0b111:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Flusher
			http.Hijacker
		}{wrapped, wrapped, wrapped, wrapped}
	case 0b1000:
		return struct {
			http.ResponseWriter
			io.ReaderFrom
		}{wrapped, wrapped}
	case 0b1001:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
		}{wrapped, wrapped, wrapped}
	case 0b1010:
		return struct {
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
		}{wrapped, wrapped, wrapped}
	case 0b1011:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Flusher
			io.ReaderFrom
		}{wrapped, wrapped, wrapped, wrapped}
	case 0b1100:
		return struct {
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
		}{wrapped, wrapped, wrapped}
	case 0b1101:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
		}{wrapped, wrapped, wrapped, wrapped}
	case 0b1110:
		return struct {
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
		}{wrapped, wrapped, wrapped, wrapped}
	case 0b1111:
		return struct {
			http.ResponseWriter
			http.CloseNotifier
			http.Flusher
			http.Hijacker
			io.ReaderFrom
		}{wrapped, wrapped, wrapped, wrapped, wrapped}
	}
	return v
}
